### ISSUE TITLE
Use Help menu for quick access

### ISSUE THREAD

**Issue by pglevy** [sethlilly/Font-Awesome-Symbols-for-Sketch#2]
This may be obvious to some, but you might add to readme that you can type keywords into the Search under the Help menu to quickly find and add symbols instead of scrolling through the list. Thanks for this!

**Comment by sethlilly** [comment]
Yes! That's coming along with the next update. Thanks for the suggestion!

**Comment by pglevy** [comment]
Actually, you can already do this now. Looks like it's part of the OS.

**Comment by sethlilly** [comment]
Yes, though it's a feature of Sketch, not OS X. I meant the documentation is coming with the next update. Sorry for the confusion.
